Repository atomist/sdm-core, pull requests merged in 2018-10, with the labels that each got.

#68 Remove Builder indirection
  index.ts
  lib/goal/common/Build.ts
  lib/internal/delivery/build/local/AtomistBuildStatusUpdater.ts
  lib/internal/delivery/build/local/LocalBuilder.ts
  lib/internal/delivery/build/local/executeBuild.ts
  lib/internal/delivery/build/local/lein/leinBuilder.ts
  lib/internal/delivery/build/local/spawnBuilder.ts
  package-lock.json
  package.json
  test/internal/delivery/build/local/lein/leinBuilder.test.ts
  test/internal/machine/HandlerBasedSoftwareDeliveryMachine.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, breaking, changelog:changed

#70 Remove Atomist pre-code-build hook
  .atomist/hooks/pre-code-build
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:removed

#75 Move goals into subscription
  lib/graphql/fragment/SdmGoalWithGoalsFields.graphql
  lib/graphql/subscription/OnAnyCompletedSdmGoal.graphql
  lib/graphql/subscription/OnAnyFailedSdmGoal.graphql
  lib/graphql/subscription/OnAnySuccessfulSdmGoal.graphql
  lib/handlers/events/delivery/goals/RequestDownstreamGoalsOnGoalSuccess.ts
  lib/handlers/events/delivery/goals/RespondOnGoalCompletion.ts
  lib/handlers/events/delivery/goals/SkipDownstreamGoalsOnGoalFailure.ts
  lib/internal/machine/HandlerBasedSoftwareDeliveryMachine.ts
  package-lock.json
  package.json
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#77 Add commit-images link to GraphQL
  lib/graphql/fragment/PushFields.graphql
Labels: auto-merge:on-approve, changelog:changed
