Repository atomist/sdm-core, pull requests merged in 2018-08, with the labels that each got.

#30 Remove cloud foundry pack
  legal/THIRD_PARTY.md
  package-lock.json
  package.json
  src/index.ts
  src/pack/pcf/CloudFoundryApi.ts
  src/pack/pcf/CloudFoundryBlueGreenDeployer.ts
  src/pack/pcf/CloudFoundryBlueGreener.ts
  src/pack/pcf/CloudFoundryManifest.ts
  src/pack/pcf/CloudFoundryPushDeployer.ts
  src/pack/pcf/CloudFoundryPusher.ts
  src/pack/pcf/CloudFoundryTarget.ts
  src/pack/pcf/CommandLineCloudFoundryDeployer.ts
  src/pack/pcf/EnvironmentCloudFoundryTarget.ts
  src/pack/pcf/ProjectArchiver.ts
  src/pack/pcf/cloudFoundryLogParser.ts
  src/pack/pcf/cloudFoundryManifestPushTest.ts
  test/pack/pcf/cloudFoundryLogParserTest.ts
Labels: atomist:merge-on-approve

#34 Move local configuration into configuration object
  package-lock.json
  package.json
  src/handlers/events/delivery/goals/FulfillGoalOnRequested.ts
  src/index.ts
  src/internal/delivery/build/local/SpawnBuilder.ts
  src/internal/delivery/goals/support/githubStatusSummarySupport.ts
  src/internal/machine/LocalSoftwareDeliveryMachineOptions.ts
  src/internal/machine/configureSdm.ts
  src/internal/util/startupMessage.ts
  src/machine/defaultSoftwareDeliveryMachineConfiguration.ts
  src/util/misc/result.ts
  test/util/misc/resultTest.ts
Labels: auto-merge:on-approve, breaking, changelog:changed

#35 Update to match SDM auto inspect PR
  package-lock.json
  package.json
  src/pack/well-known-goals/addWellKnownGoals.ts
  src/pack/well-known-goals/httpServiceGoals.ts
  src/pack/well-known-goals/libraryGoals.ts
  test/pack/graph-goals/graphGoalsTest.ts
Labels: auto-merge-method:squash, auto-merge:on-approve
