Repository atomist/sdm-core, pull requests merged in 2018-09, with the labels that each got.

#40 Update to latest master
  package-lock.json
  package.json
  src/handlers/commands/DisplayDeployEnablement.ts
  src/handlers/commands/ShowBuildLog.ts
  src/handlers/events/delivery/goals/k8s/launchGoalK8.ts
  src/internal/delivery/build/local/LocalBuilder.ts
  src/internal/delivery/code/fingerprint/executeFingerprinting.ts
  src/log/DashboardDisplayProgressLog.ts
  src/util/webhook/sendFingerprintToAtomist.ts
  test/log/DashboardDisplayProgressLogTest.ts
Labels: auto-merge:on-approve

#41 Allow goals to receive implementations and listeners
  package-lock.json
  package.json
  src/handlers/commands/DisplayDeployEnablement.ts
  src/handlers/commands/ShowBuildLog.ts
  src/handlers/events/delivery/goals/FulfillGoalOnRequested.ts
  src/handlers/events/delivery/goals/GoalAutomationEventListener.ts
  src/handlers/events/delivery/goals/RequestDownstreamGoalsOnGoalSuccess.ts
  src/handlers/events/delivery/goals/SetGoalsOnPush.ts
  src/handlers/events/delivery/goals/resetGoals.ts
  src/index.ts
  src/internal/delivery/code/fingerprint/executeFingerprinting.ts
  src/internal/machine/HandlerBasedSoftwareDeliveryMachine.ts
  src/internal/machine/configureSdm.ts
  src/machine/defaultSoftwareDeliveryMachineConfiguration.ts
  src/pack/well-known-goals/addWellKnownGoals.ts
  src/pack/well-known-goals/commonGoals.ts
  src/pack/well-known-goals/httpServiceGoals.ts
  src/pack/well-known-goals/libraryGoals.ts
  test/blueprint/sdmGoalImplementationTest.ts
  test/internal/machine/HandlerBasedSoftwareDeliveryMachineTest.ts
  test/pack/graph-goals/graphGoalsTest.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#44 Moved docker functionality to separate pack
  src/index.ts
  src/pack/docker/dockerPushTests.ts
  src/pack/docker/executeDockerBuild.ts
Labels: auto-merge:on-approve

#49 FingerprintInvocation contains a vector of Fingerprints
  package-lock.json
  package.json
  src/util/webhook/sendFingerprintToAtomist.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#48 Prepare to hook in client startup events
  package-lock.json
  package.json
  src/goal/common/Tag.ts
  src/goal/common/Version.ts
  src/handlers/events/delivery/goals/GoalAutomationEventListener.ts
  src/internal/machine/InvokeSdmStartupListenersAutomationEventListener.ts
  src/internal/machine/configureSdm.ts
  test/blueprint/sdmGoalImplementationTest.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#57 Allow using async function to create SDM
  lib/internal/machine/configureSdm.ts
Labels: auto-merge:on-approve, changelog:added

#59 New states for stopped and canceled goals
  lib/graphql/schema.json
  lib/graphql/subscription/OnAnyFailedSdmGoal.graphql
  lib/handlers/events/delivery/goals/SkipDownstreamGoalsOnGoalFailure.ts
  package-lock.json
  package.json
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#62 Export packs from the index as packs
  index.ts
  lib/pack/build-aware-transform/buildAwareTransform.ts
  lib/pack/build-aware-transform/index.ts
  lib/pack/build-aware-transform/support/buildAwareBuildListener.ts
  lib/pack/build-aware-transform/support/makeBuildAware.ts
  lib/pack/goal-state/index.ts
  lib/pack/index.ts
  lib/pack/info/index.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, breaking, changelog:added

#63 Support for code level project listeners
  lib/handlers/events/delivery/goals/FulfillGoalOnRequested.ts
  lib/internal/delivery/build/local/LocalBuilder.ts
  lib/internal/delivery/build/local/SpawnBuilder.ts
  package-lock.json
  package.json
Labels: auto-merge:on-approve, changelog:added

#67 Remove well known goals
  lib/goal/common/Tag.ts
  lib/goal/common/Version.ts
  lib/internal/machine/HandlerBasedSoftwareDeliveryMachine.ts
  package-lock.json
  package.json
  test/blueprint/sdmGoalImplementation.test.ts
  test/internal/artifact/github/GitHubReleaseArtifactStore.test.ts
  test/internal/delivery/build/local/lein/leinBuilder.test.ts
  test/internal/delivery/goals/support/validateGoal.test.ts
  test/internal/machine/HandlerBasedSoftwareDeliveryMachine.test.ts
  test/log/DashboardDisplayProgressLog.test.ts
  test/log/RolarProgressLog.test.ts
  test/mapping/pushtest/toPublicRepo.test.ts
  test/util/fingerprint/elementRequest.test.ts
  test/util/slack/diffRendering.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, breaking, changelog:removed
