Repository atomist/sdm-core, pull requests merged in 2019-05, with the labels that each got.

#146 Support for goal contributions as data
  index.ts
  lib/machine/configure.ts
  test/machine/configure.test.ts
Labels: auto-merge:on-approve, changelog:added

#147 Deprecates deployer and artifact usage
  lib/internal/artifact/github/GitHubReleaseArtifactStore.ts
  lib/internal/artifact/local/EphemeralLocalArtifactStore.ts
  lib/internal/delivery/deploy/local/LocalDeployerOptions.ts
  lib/internal/delivery/deploy/local/ManagedDeployments.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed, changelog:deprecated

#149 Reorder token resolution
  lib/handlers/common/GitHubCredentialsResolver.ts
  test/handlers/common/GitHubCredentialsResolver.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:changed

#155 Replace process.exit with safeExit
  lib/graphql/mutation/DeleteTeamConfiguration.graphql
  lib/handlers/events/delivery/goals/CancelGoalOnCanceled.ts
  lib/handlers/events/delivery/goals/GoalAutomationEventListener.ts
  lib/internal/artifact/github/GitHubReleaseArtifactStore.ts
  lib/internal/artifact/local/EphemeralLocalArtifactStore.ts
  package-lock.json
  package.json
Labels: auto-merge-method:merge, auto-merge:on-approve, auto-rebase:on-push, changelog:fixed

#159 Differentiate between goal and handler results
  lib/handlers/events/delivery/goals/FulfillGoalOnRequested.ts
  lib/handlers/events/delivery/goals/GoalAutomationEventListener.ts
  lib/pack/k8s/KubernetesGoalScheduler.ts
  package-lock.json
  package.json
Labels: auto-merge-method:merge, auto-merge:on-approve, auto-rebase:on-push, changelog:changed
