Repository atomist/sdm-core, pull requests merged in 2019-10, with the labels that each got.

#199 Add type for configure argument
  lib/machine/configure.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, auto-rebase:on-push, changelog:added

#200 Introduce universal generators
  index.ts
  lib/pack/universal-generator/generator.ts
  lib/pack/universal-generator/generatorSupport.ts
  lib/pack/universal-generator/test/assertGenerator.ts
  package-lock.json
  package.json
  test/pack/universal-generator/universalGenerator.test.ts
Labels: auto-branch-delete:on-close, auto-merge-method:merge, auto-merge:on-approve, auto-rebase:on-push, changelog:added, enhancement

#205 Use git to tag
  index.ts
  lib/goal/common/Tag.ts
  lib/goal/container/util.ts
  lib/handlers/events/delivery/goals/k8s/CacheCleanupAutomationEventListener.ts
  lib/internal/delivery/build/executeTag.ts
  lib/internal/delivery/build/local/projectVersioner.ts
  package-lock.json
  package.json
Labels: auto-merge-method:merge, auto-merge:on-approve, auto-rebase:on-push, changelog:changed
