Repository atomist/sdm-core, pull requests merged in 2019-06, with the labels that each got.

#171 Add initial support for jobs
  index.ts
  lib/graphql/mutation/CreateJob.graphql
  lib/graphql/mutation/SetJobTaskState.graphql
  lib/graphql/schema.json
  lib/graphql/subscription/OnAnyJobTask.graphql
  lib/machine/machineFactory.ts
  lib/pack/job/createJob.ts
  lib/pack/job/executeTask.ts
  lib/pack/job/job.ts
  package-lock.json
  package.json
  test/pack/job/createJob.test.ts
  test/pack/job/executeTask.test.ts
Labels: auto-merge-method:merge, auto-merge:on-check-success, auto-rebase:on-push, changelog:added

#173 Add id's to repo, branch and org for fingerprinting
  lib/graphql/fragment/CoreRepoFieldsAndChannels.graphql
Labels: auto-merge:on-approve, auto-rebase:on-push

#166 Add container goal
  index.ts
  lib/goal/cache/CompressingGoalCache.ts
  lib/goal/cache/goalCaching.ts
  lib/goal/container/container.ts
  lib/goal/container/docker.ts
  lib/goal/container/k8s.ts
  lib/goal/container/util.ts
  lib/pack/k8s/KubernetesGoalScheduler.ts
  lib/pack/k8s/KubernetesJobDeletingGoalCompletionListener.ts
  package-lock.json
  package.json
  test/goal/cache/CompressingGoalCache.test.ts
  test/goal/cache/goalCaching.test.ts
  test/goal/container/docker.test.ts
  test/goal/container/k8s.test.ts
  test/goal/container/util.test.ts
  test/goal/container/util.ts
  test/mapping/pushtest/toPublicRepo.test.ts
  test/pack/k8s/KubernetesGoalScheduler.test.ts
Labels: auto-merge-method:merge, auto-merge:on-check-success
