Repository atomist/sdm-core, pull requests merged in 2019-09, with the labels that each got.

#191 Upgrade to graphql-codegen version 1.7.1
  lib/handlers/events/delivery/goals/FulfillGoalOnRequested.ts
  lib/handlers/events/delivery/goals/RequestDownstreamGoalsOnGoalSuccess.ts
  lib/handlers/events/delivery/goals/SkipDownstreamGoalsOnGoalFailure.ts
  lib/internal/artifact/github/GitHubReleaseArtifactStore.ts
  lib/internal/artifact/local/EphemeralLocalArtifactStore.ts
  lib/internal/delivery/deploy/local/LocalDeployerOptions.ts
  lib/internal/delivery/deploy/local/ManagedDeployments.ts
  lib/internal/signing/goalSigning.ts
  package-lock.json
  package.json
  test/internal/signing/goalSigning.test.ts
  test/pack/job/executeTask.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#193 Apply target for lodash
  package-lock.json
  package.json
Labels: auto-branch-delete:on-close, auto-merge-method:squash, auto-merge:on-check-success

#197 More logging for NoOp GoalCache
  lib/goal/cache/NoOpGoalCache.ts
Labels: auto-merge-method:squash, auto-merge:on-approve

#198 Make output less verbose during development
  lib/goal/container/k8s.ts
  lib/handlers/events/delivery/goals/FulfillGoalOnRequested.ts
  lib/handlers/events/delivery/goals/GoalAutomationEventListener.ts
  lib/handlers/events/delivery/goals/RequestDownstreamGoalsOnGoalSuccess.ts
  lib/internal/signing/goalSigning.ts
  lib/pack/github-goal-status/statusSetters.ts
  lib/pack/goal-state/goalState.ts
  lib/pack/k8s/KubernetesGoalScheduler.ts
  lib/util/github/ghub.ts
  lib/util/webhook/ImageLink.ts
Labels: auto-branch-delete:on-close, auto-merge-method:merge, auto-merge:on-approve, changelog:changed
