Repository atomist/sdm-core, pull requests merged in 2019-12, with the labels that each got.

#219 Add placeholder replacement in cache classifier
  lib/goal/cache/CompressingGoalCache.ts
  lib/goal/cache/FileSystemGoalCacheArchiveStore.ts
  lib/goal/container/execute.ts
  lib/machine/yaml/mapGoals.ts
  lib/machine/yaml/resolvePlaceholder.ts
  package.json
  test/goal/cache/CompressingGoalCache.test.ts
  test/goal/cache/goalCaching.test.ts
  test/machine/yaml/mapGoals.test.ts
  test/machine/yaml/resolvePlaceholder.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:added

#222 Scope cache by workspace
  lib/goal/cache/CompressingGoalCache.ts
  test/goal/cache/CompressingGoalCache.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:changed

#224 Provide more context when requiring fails
  lib/machine/yaml/configureYaml.ts
  lib/machine/yaml/mapGoals.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:added

#226 Move to using GraphQL mutations for SdmGoal and SdmGoalSet
  index.ts
  lib/goal/container/util.ts
  lib/graphql/mutation/UpdateSdmVersion.graphql
  lib/handlers/events/delivery/goals/goalExecution.ts
  lib/ingesters/sdmVersionIngester.ts
  lib/internal/delivery/build/local/projectVersioner.ts
  lib/internal/delivery/deploy/local/LocalDeployerOptions.ts
  lib/internal/delivery/deploy/local/ManagedDeployments.ts
  lib/internal/machine/configureSdm.ts
  lib/internal/signing/goalSigning.ts
  lib/internal/signing/rsaGoalSigning.ts
  lib/log/RolarProgressLog.ts
  lib/pack/goal-state/cancelGoals.ts
  lib/pack/goal-state/manageGoalSets.ts
  lib/pack/goal-state/updateGoal.ts
  lib/util/github/gitHubTagRouter.ts
  lib/util/webhook/ImageLink.ts
  package-lock.json
  package.json
  test/internal/signing/goalSigning.test.ts
  test/machine/yaml/mapGoals.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed, enhancement

#227 Better YAML format
  lib/goal/cache/goalCaching.ts
  lib/goal/common/item.ts
  lib/goal/container/buildingContainer.ts
  lib/goal/container/container.ts
  lib/goal/container/repositoryDrivenContainer.ts
  lib/machine/yaml/configureYaml.ts
  lib/machine/yaml/mapGoals.ts
  lib/machine/yaml/mapPushTests.ts
  lib/machine/yaml/mapRules.ts
  test/goal/cache/goalCaching.test.ts
  test/machine/yaml/mapGoals.test.ts
  test/machine/yaml/mapPushTests.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, breaking, changelog:changed, enhancement

#229 Merge pod affinity rather than overwrite
  lib/pack/k8s/KubernetesGoalScheduler.ts
  test/pack/k8s/KubernetesGoalScheduler.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:changed

#230 Prepare for GCF to k8s goal scheduling
  lib/goal/container/buildingContainer.ts
  lib/goal/container/container.ts
  lib/goal/container/k8s.ts
  lib/goal/container/util.ts
  lib/graphql/query/InProcessSdmGoals.graphql
  lib/machine/yaml/mapGoals.ts
  lib/pack/k8s/KubernetesFulfillmentGoalScheduler.ts
  test/goal/container/k8s.test.ts
  test/machine/yaml/mapGoals.test.ts
  test/pack/k8s/KubernetesFulfillmentGoalScheduler.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:changed

#231 Add goal to fulfill scheduled container goals
  index.ts
  lib/goal/cache/goalCaching.ts
  lib/goal/common/item.ts
  lib/goal/container/container.ts
  lib/goal/container/k8s.ts
  lib/handlers/events/delivery/goals/FulfillGoalOnRequested.ts
  lib/pack/k8s/KubernetesFulfillmentGoalScheduler.ts
  test/pack/k8s/KubernetesFulfillmentGoalScheduler.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:added
