Repository atomist/sdm-core, pull requests merged in 2019-04, with the labels that each got.

#110 Artifact caching
  index.ts
  lib/goal/cache/FileSystemGoalCache.ts
  lib/goal/cache/goalCaching.ts
  lib/machine/defaultSoftwareDeliveryMachineConfiguration.ts
  test/goal/cache/FileSystemGoalCache.test.ts
  test/goal/cache/goalCaching.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve

#122 Enable multiple cache miss listeners and add a no-op cache
  index.ts
  lib/goal/cache/NoOpGoalCache.ts
  lib/goal/cache/goalCaching.ts
  package-lock.json
  test/goal/cache/FileSystemGoalCache.test.ts
  test/goal/cache/goalCaching.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#125 Caching can now also handle complete directories
  lib/goal/cache/FileSystemGoalCache.ts
  lib/goal/cache/goalCaching.ts
  test/goal/cache/FileSystemGoalCache.test.ts
  test/goal/cache/goalCaching.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#130 Enforced sdm local cache path on FileSystemGoalCache
  index.ts
  lib/goal/cache/CompressingGoalCache.ts
  lib/goal/cache/FileSystemGoalCache.ts
  lib/goal/cache/FileSystemGoalCacheArchiveStore.ts
  lib/goal/cache/goalCaching.ts
  lib/machine/defaultSoftwareDeliveryMachineConfiguration.ts
  test/goal/cache/CompressingGoalCache.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#133 Add support for sending notifications on certain goal states
  index.ts
  lib/goal/cache/CompressingGoalCache.ts
  lib/graphql/fragment/CoreRepoFieldsAndChannels.graphql
  lib/graphql/fragment/PersonFields.graphql
  lib/graphql/fragment/PushFields.graphql
  lib/machine/machineFactory.ts
  lib/pack/github-goal-status/github.ts
  lib/pack/goal-state/goalState.ts
  lib/pack/goal-state/updateGoal.ts
  lib/pack/info/exposeInfo.ts
  lib/pack/k8s/goalScheduling.ts
  lib/pack/notification/notification.ts
  package-lock.json
  package.json
  test/goal/cache/goalCaching.test.ts
  test/pack/notification/notification.test.ts
Labels: auto-merge:on-check-success, changelog:added, enhancement

#134 Make tests safer, eliminate some axios use
  lib/internal/artifact/github/GitHubReleaseArtifactStore.ts
  lib/internal/delivery/deploy/local/ManagedDeployments.ts
  lib/util/github/ghub.ts
  lib/util/github/gitHubTagRouter.ts
  lib/util/verify/lookFor200OnEndpointRootGet.ts
  package-lock.json
  package.json
  test/internal/artifact/github/GitHubReleaseArtifactStore.test.ts
  test/log/RolarProgressLog.test.ts
  test/mapping/pushtest/toPublicRepo.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:changed
